[package]
name = "bevy_godot4_proc_macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
# bevy_godot4 = { path = "../"}
syn = { version = "1.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"